# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Face_Reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 583)
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(180, 20, 640, 480))
        self.image_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_label.setText("")
        self.image_label.setTextFormat(QtCore.Qt.AutoText)
        self.image_label.setScaledContents(False)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.OpenCamera_pushButton = QtWidgets.QPushButton(Form)
        self.OpenCamera_pushButton.setGeometry(QtCore.QRect(50, 90, 75, 23))
        self.OpenCamera_pushButton.setObjectName("OpenCamera_pushButton")
        self.CloseCamera_pushButton = QtWidgets.QPushButton(Form)
        self.CloseCamera_pushButton.setGeometry(QtCore.QRect(50, 150, 75, 23))
        self.CloseCamera_pushButton.setObjectName("CloseCamera_pushButton")
        self.FaceReg_pushButton = QtWidgets.QPushButton(Form)
        self.FaceReg_pushButton.setGeometry(QtCore.QRect(50, 210, 75, 23))
        self.FaceReg_pushButton.setObjectName("FaceReg_pushButton")
        self.addFace_pushButton = QtWidgets.QPushButton(Form)
        self.addFace_pushButton.setGeometry(QtCore.QRect(50, 270, 75, 23))
        self.addFace_pushButton.setObjectName("addFace_pushButton")
        self.genFaceLib_pushButton = QtWidgets.QPushButton(Form)
        self.genFaceLib_pushButton.setGeometry(QtCore.QRect(50, 330, 75, 23))
        self.genFaceLib_pushButton.setObjectName("genFaceLib_pushButton")
        self.getFaceInfo_pushButton = QtWidgets.QPushButton(Form)
        self.getFaceInfo_pushButton.setGeometry(QtCore.QRect(50, 390, 75, 23))
        self.getFaceInfo_pushButton.setObjectName("getFaceInfo_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Face Reg"))
        self.OpenCamera_pushButton.setText(_translate("Form", "打开摄像头"))
        self.CloseCamera_pushButton.setText(_translate("Form", "关闭摄像头"))
        self.FaceReg_pushButton.setText(_translate("Form", "人脸识别"))
        self.addFace_pushButton.setText(_translate("Form", "添加人脸"))
        self.genFaceLib_pushButton.setText(_translate("Form", "生成人脸库"))
        self.getFaceInfo_pushButton.setText(_translate("Form", "人脸信息"))
